<?php
/**
 * Created by PhpStorm.
 * User: jonatan
 * Date: 04/12/2018
 * Time: 17:12
 */

namespace App\Test\Model\Cell;



use App\Model\Neighbours;

class GenerationDeadTest extends CellHelper
{
    private $deadCell;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->deadCell =  $this->getADeadCell();
    }



    public function testBecomesAlive()
   {

       $populationForBecomesAlive = [3];

       foreach($populationForBecomesAlive as $numberOfNeighbours){
           $this->cellGenerationIsOk($this->getADeadCell(),$numberOfNeighbours,self::ALIVE);
       }

   }

   public function testContinuesDead()
   {
       $populationForContinuousDead = [0,1,2,4,5,6,7,8];

       foreach($populationForContinuousDead as $numberOfNeighbours){
           $this->cellGenerationIsOk($this->getADeadCell(),$numberOfNeighbours,self::DEAD);
       }
   }





}
