<?php
/**
 * Created by PhpStorm.
 * User: jonatan
 * Date: 04/12/2018
 * Time: 18:35
 */

namespace App\Test\Model;

use App\Model\Cell;
use App\Model\Grid;
use App\Test\Model\Grid\GridHelper;
use PHPUnit\Framework\TestCase;

/**
 * Class GeneratioNTest
 * @package App\Test\Model
 * @property Grid $grid
 */
class GenerationTest extends GridHelper
{
    private $grid;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->grid = Grid::factory(3,3,Cell::ALIVE);
    }

    public function testGeneration()
    {
        $this->assertEquals(9,$this->grid->alive());

        $this->grid->nextGeneration();

        $secondGeneration = <<<EOD
3 3
* . *
. . .
* . *
EOD;
        $this->assertEquals($secondGeneration,$this->grid->toString());

        $thirdGeneration = <<<EOD
3 3
. . .
. . .
. . .
EOD;
        $this->grid->nextGeneration();
        $this->assertEquals($thirdGeneration,$this->grid->toString());
    }


}
