<?php
/**
 * Created by PhpStorm.
 * User: jonatan
 * Date: 04/12/2018
 * Time: 18:35
 */

namespace App\Test\Model;

use App\Model\Grid;
use App\Test\Model\Grid\GridHelper;
use PHPUnit\Framework\TestCase;

/**
 * Class GetNeighboursTest
 * @package App\Test\Model
 * @property Grid $grid
 */
class GetCellTest extends GridHelper
{
    private $grid;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->grid = Grid::factory(2,2);
    }

    public function testValidCell()
    {
        $cell = $this->grid->getCell(0,0);

        $this->assertNotEmpty($cell);

        $this->assertEquals(0,$cell->getPosX());
        $this->assertEquals(0,$cell->getPosY());

    }

    public function testAnotherValidCell()
    {
        $cell = $this->grid->getCell(1,1);

        $this->assertNotEmpty($cell);

        $this->assertEquals(1,$cell->getPosX());
        $this->assertEquals(1,$cell->getPosY());

    }


    public function testMissingCell()
    {
        $this->expectExceptionMessage('Cell not found');
        $this->grid->getCell(50,50);

    }


}
