<?php
/**
 * Created by PhpStorm.
 * User: jonatan
 * Date: 04/12/2018
 * Time: 18:35
 */

namespace App\Test\Model;

use App\Model\Cell;
use App\Model\Grid;
use App\Test\Model\Grid\GridHelper;
use PHPUnit\Framework\TestCase;

/**
 * Class GeneratioNTest
 * @package App\Test\Model
 * @property Grid $grid
 */
class GetGenerationTest extends GridHelper
{
    private $grid;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->grid = Grid::factory(3,3,Cell::ALIVE);
    }

    public function testGetGeneration()
    {
        $generation = 1;
        $this->assertEquals($generation,$this->grid->getGeneration());

        $this->grid->nextGeneration();
        $generation++;

        $this->assertEquals($generation,$this->grid->getGeneration());
    }

}
